### ISSUE TITLE
Make it work in more browsers than just Chrome

### ISSUE THREAD

**Issue by chrishutchinson** [times/cardkit#22]
Yeah, that's probably pretty important.

**Comment by aendrew** [comment]
THERE ARE BROWSERS OTHER THAN CHROME?!!?! :scream:

**Comment by chrishutchinson** [comment]
It now works on Firefox! Still a few issues on Safari (appears to be a security issue with `toDataURL` or something about the data URI referencing external files - maybe I should find a way to exclude those and test...) and IE (eh, that's not a suprise).

**Comment by sarvjeet** [comment]
Well, I tested the compiled version in dist today and image download does not work on Safari 9. The issue is with the images in the svg. If you create a card with no logo, it works fine.

Anyone who can tell me what could be happening?
