### ISSUE TITLE
Font-awesome broken? 

### ISSUE THREAD

**Issue by KKDeep** [times/cardkit#32]
Just observed the Font-awesome fonts are not showing up. It used to work yesterday.

**Comment by chrishutchinson** [comment]
On the GitHub hosted version or your own local copy? I'm still seeing them.

If you can attach a screenshot that'd be useful.

**Comment by KKDeep** [comment]
Local as well as the Github hosted. Here is the screenshot
![screenshot from 2015-06-03 14 39 09](https://cloud.githubusercontent.com/assets/1812737/7956617/a2ba98d4-09fe-11e5-8f91-112e040e42f8.png)

Fonts on the other site (my server) are working fine so this doesn't seems to be a browser issue. Here I have used fa-users.
![screenshot from 2015-06-03 14 42 26](https://cloud.githubusercontent.com/assets/1812737/7956649/01e3bc96-09ff-11e5-85cc-27433a9a2afa.png)
