### ISSUE TITLE
Provide a way to configure elements

### ISSUE THREAD

**Issue by rdebeasi** [times/cardkit#40]
It would be really useful to be able to configure the elements that make up a card (currently stored in main.js). For example, the demo GIF shows a "name" element that isn't included in the app by default. That would need to be added to elements in main.js, right?

It would also be useful to be able to create predefined sets of elements for different types of cards: quote cards, photo watermarks, etc. The user could then select a "type" of card to bring up different sets of elements.

Would you accept a pull request for this sort of functionality?

Thanks very much for creating and open-sourcing CardKit! It's a fantastic tool.

**Comment by chrishutchinson** [comment]
Hey @rdebeasi,

The main intention is that you would fork your own version of CardKit and configure the elements as you or your organisation require - effectively modifying `main.js` to add your own elements. You then deploy this modified version of CardKit to your own server, or to GitHub pages. I think this is the solution to your first question.

Your second question, if I understand correctly, is about pre-defined card layouts (e.g. quote cards, watermark cards etc.). CardKit itself is intended to be a blank slate, so developers can configure it however they need, without any pre-configured layouts. However, I think there is a use case for a non-developer version that has a range of 'default' card layouts that anyone (with no development skills) could dive straight into and start using.

To do this, I envisage CardKit as a Service (CaaS), a web app with simple authentication that allows users to create cards, view them, update them and delete them. They would be able to select from a range of defaults layouts when creating each card, as you suggest, which would then define the elements they can select.

This is something I've thought about for a while, but haven't yet made any progress towards, but would definitely like to in the near future. Does this sound like the sort of thing you're thinking of?

**Comment by rdebeasi** [comment]
Thanks so much for the detailed reply! I was thinking of a tool that could be configured by developers, but CaaS sounds even better.

Do you think support for multiple layouts (configured by developers for now) might be a good intermediate step between the current app and CaaS?

We're also considering creating a CardKit plugin for WordPress. This plugin would allow users to configure themes (and maybe layouts) within WordPress. Users could build cards with images from the media library.

Feel free to close this ticket if you'd like - it sounds like this feature isn't in the cards (har!) for now, but it might be the basis for a future project. Thanks again!
