### ISSUE TITLE
Select (logo) image source from dropdown?

### ISSUE THREAD

**Issue by raphaelcockx** [times/cardkit#42]
Hi, really loving Cardkit and really nice to see how much easier it's gotten to configure all the things.

Just one thing I'm missing: it's be super great if I could specify a dropdown list of image sources/sizes just like I can for the fontsize of text elements.

The reason is that while a certain theme (corresponding to a brand the way we use Cardkit) will mostly be used with a certain logo, this could occasionally change. For instance, because a black and white logo of that brand would fit better with the background image.

Right now, as I understand it, I'm supposed to either duplicate the theme in themes.config,json for every combination or ask users to upload images themselves. None of those options is really ideal.

**Comment by chrishutchinson** [comment]
Hey @raphaelcockx,

If I've understood what you mean, you want a dropdown to set an images source, rather than an uploadable area. If that is what you want, it's definitely a valid request, so valid in fact that I've added it myself in a private fork. It effectively would allow you to set `editable.src` of an element as an object of key value pairs. Example of an image element config below:

    {
        name: 'Image select',
        type: 'image',
        width: 100,
        height: 100,
        src: '',
        x: 100,
        y: 100,
        preserveAspectRatio: 'xMinYMin meet',
        draggable: true,
        editable: {
            src: {
                'Image one': '{source of image one}',
                'Image two': '{source of image two}'
            }
        }
    }

I'm planning to bring this into the core CardKit version very soon (hopefully next week), so I'll keep this issue up to date!

Let me know if I've misunderstood though!

**Comment by raphaelcockx** [comment]
Thanks @chrishutchinson, that is in fact **exactly** what I meant. Looking forward to try it our very soon.

**Comment by chrishutchinson** [comment]
Hey @raphaelcockx,

I've just pushed a new version (v1.1.0) to the `master` branch, which has the above functionality. If you look at the demo theme configuration you should see an example of this. I'll be pushing the demo version to http://times.github.io/cardkit shortly.

There are a few other changes you might need to make to your config, and having never released a new version to CardKit I'm not sure how easy the upgrade path will be, but feel free to play around with the new version and let me know how you get on.

**Comment by raphaelcockx** [comment]
Thanks @chrishutchinson. I've been very busy with other projects so far this week, but will look into the new version as soon as I can. I see some other stuff in the release notes that might be useful for us as well.

I didn't get very far on the configuration anyway, so I'm not sure whether I'll run into very many problems nor how typical that would be for someone upgrading from a fully configured 1.0.0.
