### ISSUE TITLE
[question] Does this support any kind of compression ?

### ISSUE THREAD

**Issue by jpvalery** [times/cardkit#44]
Hey,

I was just wondering if CardKit was supporting any type of compression ? 
Is the image issued compressed, or is it an additional step to take ?

Thanks a lot !

**Comment by chrishutchinson** [comment]
Hey @jpvalery,

No compression on CardKit's side, other than you can specify in the config if you want it at 1x, 2x or 3x resolution.

The intention is that if it's being uploaded somewhere (e.g. Twitter, Facebook, internal CMS) then that service would do any appropriate cropping, resizing and optimisation.

What's your use case?

**Comment by jpvalery** [comment]
Hey,

Thanks for the reactivity :+1: 

The use would be for uploading on WordPress websites. To allow our team of writers to have a simple online tool rather than play with Photoshop.
I think Ruby support compression of JPEGs, hence my question :)

Thanks,

**Comment by chrishutchinson** [comment]
I see what you mean!

Might be worth running something like https://en-gb.wordpress.org/plugins/wp-smushit/ on your WordPress install. Any images that get uploaded will be optimised on upload (along with WordPress' default resizing etc.)

Would that help solve your issue?

**Comment by jpvalery** [comment]
Hey,

Thanks for the reply.
We have tested this kind of plugins in the past and weren't happy with the performances and resources consumption.

But don't worry, CardKit still look great and we'll find a workaround.
But that could be a "nice to have" feature :)

Thanks,

**Comment by chrishutchinson** [comment]
Yeah, I can understand that.

I'll be looking at the SVG-to-PNG functionality soon, so if there's anything I can do to optimise the output in there I will. If I achieve anything I'll let you know!

Otherwise, enjoy CardKit! Let me know if there's anything else you need while you're setting up.
