### ISSUE TITLE
Different deploy architecture: library approach

### ISSUE THREAD

**Issue by zzolo** [times/cardkit#48]
Wonderful project and appreciate the easy config object(s).

The fork-as-deploy/install is limiting though.  It makes it hard to config, override, and then upgrade the code base.  Any changes I make to my fork might cause merge errors later.

It would be really nice if this was an installable library, where one would include the library (JS/CSS) on the page, then a bit of JS to instantiate and configure.

```html
<html><body><script>var cardkit = new CardKit({ config: 'here' }); </script></body></html>
```

This would mean cardkit could be maintained in bower or npm and managed like any other dependency.

**Comment by chrishutchinson** [comment]
Hey @zzolo,

I've definitely thought about this in the past, and would love to do something like this. I'm actually in the middle of some concepting and experimenting around what an updated version of CardKit might look like, specifically looking at making the configuration process cleaner.

I'll keep this issue open as a question, and report back with my findings!

**Comment by chrishutchinson** [comment]
Hey @zzolo,

We have a new version of CardKit coming soon that works as an installable library. You can find out more here: https://github.com/times/cardkit/issues/52

**Comment by zzolo** [comment]
Awesome!  Let me know if/when I can help test it out.
