### ISSUE TITLE
Coming soon: CardKit 2

### ISSUE THREAD

**Issue by chrishutchinson** [times/cardkit#52]
Over the past few weeks we've been working on a major update to CardKit, version 2.

CardKit 2 will bring a range of new features, most notably:
- Simpler to install
- Simpler to initialise
- Bring your own UI
- Server-side rendering

You can find out more about all these features here: https://medium.com/digital-times/cardkit-2-d3dc1d06005#.c48hwcdcd

We'll be creating a new branch in the coming days that will allow developers a chance to try out CardKit 2.

If you have any questions, please log them as issues using the `cardkit-2` label.

**Comment by chrishutchinson** [comment]
A brief update for anyone that stumbles across this - we're still working hard on CardKit 2, and we're aiming for it to be out in the next couple of weeks. In the interests of openness, here's a few of the things that we're working through before releasing it into the wild:

- A full initial code review, ensuring the first version is up a high standard 
- Getting CardKit (the core along with its associated DOM and server libraries) bundled correctly so it worked via a bundler (such as Webpack), via a `<script>` tag, and in Node.js has taken longer than expected. We've got this working now, but want to test it in a few real-world contexts to ensure we haven't missed anything major
- Ensuring we have a decent base suite of tests
- Tidying up the configuration logic so we have feature parity with v1.x, along with the ability to do some exciting new tricks
- Writing up the new Wiki with details of configuration, deployment and how to transition from v1.x 

I'll update this again with our progress in the coming days, feel free to ask any questions here on on Twitter [@CardKit](http://twitter.com/cardkit) in the meantime.

**Comment by Chrisedmo** [comment]
Great to hear guys!
