### ISSUE TITLE
Smart / curly quotes?

### ISSUE THREAD

**Issue by Kirkman** [times/cardkit#67]
Is there a way to smart-ify quote marks when users are typing into text fields?

**Comment by chrishutchinson** [comment]
Yep, CardKit 2 has this out of the box.

To do so, set the `smartQuotes` property to `true` in the configuration your text layer, like so:

```
text: {
  type: 'text',
  name: 'Headline',
  x: 0,
  y: 0,
  smartQuotes: true,
  text: 'These "quotes" will be smart'
},
```

**Comment by chrishutchinson** [comment]
I have updated the [Wiki to reflect this](https://github.com/times/cardkit/wiki/Creating-your-own-configuration#text-smartquotes-bool).

**Comment by Kirkman** [comment]
It works!
