### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by fdaudens** [times/cardkit#77]
Hi Chris,

Wonderful update of Cardkit! I just have one question: you mentionned that it was possible to integrate Google Fonts, but I didn't find the info on the wiki and my trials and errors were inconclusive. What should I add where?

Thank you!

**Comment by njgriffiths** [comment]
+1 on this. Trying to get custom fonts working but not having any luck. They display in the DOM but not on the rendered cards. :-(

**Comment by chrishutchinson** [comment]
Hey both,

I've just been looking into this. I'll be making a minor release soon to make it easier to work with custom fonts (especially Google fonts), and will update the README / Wiki with details of how to do that.

@njgriffiths: To your issue specifically, this could be fixed by this change, so I'll leave this issue open so we can confirm later

**Comment by chrishutchinson** [comment]
Update: PR #80 should fix this, and adds better documentation to the README

**Comment by cantell** [comment]
Hello there. How do I call .computeFonts({...}) on the card object? I cannot seem to access the card object.

**Comment by chrishutchinson** [comment]
Hey @cantell - you shouldn't need to, as `.computeFonts()` is an internal method. What are you trying to achieve?

**Comment by cantell** [comment]
No issues anymore. I already got it working. I was trying to use custom fonts on an image. I had to read the source code. Then I saw one can actually pass the fonts object to configuration object. I do not think this is stated in the documentation.

**Comment by chrishutchinson** [comment]
Closing, see notes on #82 for improvements that should help anyone with similar issues:

https://github.com/times/cardkit/issues/82#issuecomment-316458954
