### ISSUE TITLE
Google fonts

### ISSUE THREAD

**Issue by rstevens354** [times/cardkit#82]
Can you write up the README file with a bit more detail on how you import google fonts? Maybe supply a JSFiddle...

**Comment by chrishutchinson** [comment]
Hey, hopefully [v2.0.6](https://github.com/times/cardkit/releases/tag/v2.0.6) has improved this for you! Some pointers:

- Notes on using Custom Fonts in the README: https://github.com/times/cardkit#custom-fonts
- An improved example in the `index.html` file: https://github.com/times/cardkit/blob/master/index.html

I'll close this issue, but if you still have questions, feel free to re-open it!
